import React, { useState, useEffect } from 'react';
import { GoogleGenerativeAI } from "@google/generative-ai";
import { jsPDF } from "jspdf";
import {
  Layout, Download, Sparkles, History,
  Trash2, ChevronRight, Settings, BookOpen,
  ToggleLeft, ToggleRight, FileText
} from 'lucide-react';

export default function App() {
  // --- STATE ---
  const [apiKey, setApiKey] = useState(localStorage.getItem('gemini_key') || '');
  const [transcript, setTranscript] = useState('');
  const [activityType, setActivityType] = useState('comprehension');
  const [cefrLevel, setCefrLevel] = useState('B1');
  const [isScaffolded, setIsScaffolded] = useState(false);
  const [loading, setLoading] = useState(false);

  // The "Active" Lesson
  const [activity, setActivity] = useState(null);

  // History System
  const [history, setHistory] = useState([]);

  // Load History on Mount
  useEffect(() => {
    const saved = JSON.parse(localStorage.getItem('lesson_history') || '[]');
    setHistory(saved);
  }, []);

  // Save Key
  useEffect(() => {
    localStorage.setItem('gemini_key', apiKey);
  }, [apiKey]);

  // --- ACTIONS ---

  const addToHistory = (newActivity) => {
    const newEntry = {
      id: Date.now(),
      date: new Date().toLocaleDateString(),
      ...newActivity
    };
    const updated = [newEntry, ...history];
    setHistory(updated);
    localStorage.setItem('lesson_history', JSON.stringify(updated));
  };

  const loadFromHistory = (item) => {
    setActivity(item);
    // Optional: Restore configuration too
    if (item.meta) {
      setCefrLevel(item.meta.level);
      setActivityType(item.meta.type);
    }
  };

  const clearHistory = () => {
    if (confirm("Clear all saved lessons?")) {
      setHistory([]);
      localStorage.setItem('lesson_history', '[]');
    }
  };

  // --- AI GENERATION ---
  const generateActivity = async () => {
    if (!apiKey) return alert("Please enter API Key");
    setLoading(true);

    try {
      const genAI = new GoogleGenerativeAI(apiKey);
      const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

      // PROMPT LOGIC (Same robust logic as v2.0)
      let typePrompt = "";
      switch (activityType) {
        case 'vocabulary': typePrompt = "FOCUS: VOCABULARY. Extract 8-10 difficult words. Create matching questions."; break;
        case 'grammar': typePrompt = "FOCUS: GRAMMAR. Identify tense/structures. Create fill-in-the-blanks."; break;
        case 'true_false': typePrompt = "FOCUS: TRUE/FALSE. Create 10 statements."; break;
        case 'discussion': typePrompt = "FOCUS: SPEAKING. Create discussion prompts."; break;
        default: typePrompt = "FOCUS: COMPREHENSION. Standard open questions.";
      }

      const scaffoldPrompt = isScaffolded
        ? "SCAFFOLDING: ON. Hints, Multiple Choice, Simplified Text."
        : "SCAFFOLDING: OFF. Standard.";

      const prompt = `
        You are a Lesson Architect.
        TEXT: "${transcript}"
        CONFIG: ${typePrompt} | Level: ${cefrLevel} | ${scaffoldPrompt}
        
        OUTPUT JSON ONLY:
        {
          "title": "Title",
          "meta": { "level": "${cefrLevel}", "type": "${activityType}", "duration": "20m" },
          "teacher_guide": { "rationale": "...", "key_answers": ["..."] },
          "student_worksheet": {
            "instructions": "...",
            "questions": [
              { "question_text": "...", "options": ["A","B"], "hint": "...", "type": "standard" }
            ],
            "glossary": [{ "word": "...", "definition": "..." }]
          }
        }
      `;

      const result = await model.generateContent(prompt);
      const text = result.response.text().replace(/```json/g, '').replace(/```/g, '').trim();
      const data = JSON.parse(text);

      setActivity(data);
      addToHistory(data); // Auto-save!

    } catch (err) {
      alert("Error: " + err.message);
    } finally {
      setLoading(false);
    }
  };

  // --- PRO PDF ENGINE ---
  const downloadPDF = () => {
    if (!activity) return;
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;

    // Brand Colors (Indigo & Emerald Theme)
    const primaryColor = [79, 70, 229];   // #4f46e5
    const secondaryColor = [243, 244, 246]; // #f3f4f6 (Light Gray)
    const accentColor = [16, 185, 129];     // #10b981 (Green for hints)

    // Helper: Page State
    let y = 0;
    let pageNo = 1;

    // Helper: Add Footer (Page Numbers)
    const addFooters = () => {
      const totalPages = doc.internal.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(
          `Page ${i} of ${totalPages}  |  Generated by LessonArchitect AI`,
          pageWidth / 2,
          pageHeight - 10,
          { align: 'center' }
        );
      }
    };

    // Helper: Check for Page Break
    const checkSpace = (heightNeeded) => {
      if (y + heightNeeded > pageHeight - margin) {
        doc.addPage();
        pageNo++;
        y = 20;
      }
    };

    // ==========================================
    // PAGE 1: STUDENT WORKSHEET
    // ==========================================

    // 1. HEADER BANNER
    doc.setFillColor(...primaryColor);
    doc.rect(0, 0, pageWidth, 40, 'F'); // Full width indigo bar

    // Title (White Text)
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text(activity.title, margin, 22);

    // Meta Subtitle
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(224, 231, 255); // Light indigo text
    doc.text(`${activity.meta.level}  •  ${activity.meta.type.toUpperCase()}  •  ${activity.meta.duration}`, margin, 32);

    y = 55;

    // 2. STUDENT DETAILS (Name/Date)
    doc.setDrawColor(200);
    doc.setLineWidth(0.5);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(80);

    doc.text("NAME:", margin, y);
    doc.line(margin + 15, y, margin + 85, y); // Name Line

    doc.text("DATE:", margin + 95, y);
    doc.line(margin + 110, y, pageWidth - margin, y); // Date Line
    y += 20;

    // 3. INSTRUCTIONS BOX
    doc.setFillColor(...secondaryColor);
    doc.roundedRect(margin, y, pageWidth - (margin * 2), 20, 3, 3, 'F'); // Rounded gray box

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...primaryColor);
    doc.text("INSTRUCTIONS:", margin + 5, y + 8);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(0);
    // Handle long instructions wrapping
    const instLines = doc.splitTextToSize(activity.student_worksheet.instructions, pageWidth - margin * 2 - 50);
    doc.text(instLines, margin + 40, y + 8);
    y += 35;

    // 4. QUESTIONS LOOP
    activity.student_worksheet.questions.forEach((q, i) => {
      // Estimate space needed
      let space = 20;
      if (q.options) space += (q.options.length * 8);
      checkSpace(space);

      // Styling: Number Circle
      doc.setFillColor(...primaryColor);
      doc.circle(margin + 2, y - 1.5, 4, 'F');
      doc.setTextColor(255);
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.text(`${i + 1}`, margin + 2, y - 1.2, { align: 'center', baseline: 'middle' });

      // Question Text
      doc.setTextColor(0);
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      const qLines = doc.splitTextToSize(q.question_text, pageWidth - margin - 30);
      doc.text(qLines, margin + 12, y);
      y += (qLines.length * 6) + 4;

      // Render Options
      doc.setFont("helvetica", "normal");
      if (q.options && q.options.length > 0) {
        q.options.forEach(opt => {
          checkSpace(10);
          doc.setDrawColor(100);
          doc.rect(margin + 12, y - 4, 4, 4); // Checkbox square
          doc.text(opt, margin + 20, y);
          y += 7;
        });
      }
      // Render True/False
      else if (activityType === 'true_false') {
        doc.setDrawColor(150);
        doc.roundedRect(margin + 12, y - 5, 15, 8, 1, 1);
        doc.text("TRUE", margin + 14, y);

        doc.roundedRect(margin + 40, y - 5, 15, 8, 1, 1);
        doc.text("FALSE", margin + 42, y);
        y += 10;
      }
      // Render Writing Lines
      else {
        doc.setDrawColor(220); // Very light grey
        doc.line(margin + 12, y, pageWidth - margin, y);
        doc.line(margin + 12, y + 8, pageWidth - margin, y + 8);
        y += 12;
      }

      // Hint (if Scaffolding is ON)
      if (q.hint && isScaffolded) {
        doc.setFontSize(9);
        doc.setTextColor(...accentColor);
        doc.text(`💡 Hint: ${q.hint}`, margin + 12, y - 2);
        y += 4;
      }

      y += 8; // Spacer between questions
    });

    // 5. VOCABULARY BANK (Bottom of Page)
    if (activity.student_worksheet.glossary.length > 0) {
      checkSpace(50);
      y += 5;
      doc.setDrawColor(...primaryColor);
      doc.setLineWidth(0.5);
      doc.line(margin, y, pageWidth - margin, y); // Separator line
      y += 10;

      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(...primaryColor);
      doc.text("VOCABULARY BANK", margin, y);
      y += 8;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(50);

      // Grid-like layout for vocab
      activity.student_worksheet.glossary.forEach(g => {
        checkSpace(8);
        doc.setFont("helvetica", "bold");
        doc.text(`• ${g.word}:`, margin, y);

        doc.setFont("helvetica", "normal");
        const defLines = doc.splitTextToSize(g.definition, pageWidth - margin - 60);
        doc.text(defLines, margin + 40, y);
        y += (defLines.length * 5) + 2;
      });
    }

    // ==========================================
    // PAGE 2: TEACHER'S VAULT (Answer Key)
    // ==========================================
    doc.addPage();
    y = 20;

    // Private Header
    doc.setFillColor(30, 41, 59); // Dark Slate
    doc.rect(0, 0, pageWidth, 30, 'F');
    doc.setTextColor(255);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Teacher's Guide & Answer Key", margin, 20);
    y = 50;

    // Rationale Section
    doc.setTextColor(0);
    doc.setFontSize(14);
    doc.text("Methodology", margin, y);
    y += 10;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60);
    const ratLines = doc.splitTextToSize(activity.teacher_guide.rationale, pageWidth - (margin * 2));
    doc.text(ratLines, margin, y);
    y += (ratLines.length * 5) + 15;

    // Answer Key Section
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0);
    doc.text("Answer Key", margin, y);
    y += 10;

    if (activity.teacher_guide.key_answers) {
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(0);
      activity.teacher_guide.key_answers.forEach(ans => {
        doc.text(`• ${ans}`, margin, y);
        y += 8;
      });
    }

    // Finalize with Footers
    addFooters();
    doc.save(`${activity.title.replace(/\s+/g, '_')}_Pro.pdf`);
  };

  // --- RENDER ---
  return (
    <div className="app-shell">

      {/* 1. SIDEBAR (MEMORY) */}
      <aside className="sidebar">
        <div className="brand">
          <Layout /> LessonArchitect
        </div>

        <div className="input-group" style={{ marginBottom: '20px' }}>
          <label style={{ color: '#818cf8' }}>API Key</label>
          <input
            type="password"
            value={apiKey}
            onChange={e => setApiKey(e.target.value)}
            style={{ background: 'rgba(0,0,0,0.2)', border: '1px solid #4338ca', color: 'white' }}
          />
        </div>

        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px' }}>
          <span style={{ fontSize: '0.8rem', fontWeight: 'bold', opacity: 0.7 }}>LESSON MEMORY</span>
          <button onClick={clearHistory} style={{ background: 'none', border: 'none', color: '#fb7185', cursor: 'pointer' }}><Trash2 size={14} /></button>
        </div>

        <div className="history-list">
          {history.length === 0 && <div style={{ opacity: 0.5, fontSize: '0.9rem', fontStyle: 'italic' }}>No lessons yet...</div>}
          {history.map(item => (
            <div key={item.id} className="history-item" onClick={() => loadFromHistory(item)}>
              <span className="history-title">{item.title}</span>
              <div className="history-meta">{item.meta?.level} • {item.meta?.type}</div>
            </div>
          ))}
        </div>
      </aside>

      {/* 2. MAIN WORKSPACE */}
      <main className="workspace">

        {/* LEFT: EDITOR */}
        <div className="editor-panel">
          <h2><Sparkles size={20} style={{ display: 'inline', color: '#4f46e5' }} /> New Lesson</h2>

          <div className="input-group">
            <label>Source Material</label>
            <textarea
              placeholder="Paste your text here..."
              value={transcript}
              onChange={e => setTranscript(e.target.value)}
            />
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '15px' }}>
            <div className="input-group">
              <label>Type</label>
              <select value={activityType} onChange={e => setActivityType(e.target.value)}>
                <option value="comprehension">Comprehension</option>
                <option value="vocabulary">Vocabulary</option>
                <option value="grammar">Grammar</option>
                <option value="true_false">True / False</option>
                <option value="discussion">Discussion</option>
              </select>
            </div>
            <div className="input-group">
              <label>Level</label>
              <select value={cefrLevel} onChange={e => setCefrLevel(e.target.value)}>
                <option>A1</option><option>A2</option><option>B1</option><option>B2</option><option>C1</option>
              </select>
            </div>
          </div>

          <div
            className={`toggle-box ${isScaffolded ? 'active' : ''}`}
            onClick={() => setIsScaffolded(!isScaffolded)}
          >
            {isScaffolded ? <ToggleRight color="#10b981" size={24} /> : <ToggleLeft color="#9ca3af" size={24} />}
            <div>
              <div style={{ fontWeight: 600 }}>Scaffolding Mode</div>
              <div style={{ fontSize: '0.8rem', color: '#6b7280' }}>Auto-simplify & hints</div>
            </div>
          </div>

          <button className="generate-btn" onClick={generateActivity} disabled={loading}>
            {loading ? "Constructing..." : "Generate Lesson Plan"}
          </button>
        </div>

        {/* RIGHT: LIVE PREVIEW */}
        <div className="preview-panel">
          {activity ? (
            <div className="paper">
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '20px' }}>
                <div>
                  <h1 style={{ margin: 0, fontSize: '1.8rem', color: '#111827' }}>{activity.title}</h1>
                  <div style={{ color: '#6b7280', marginTop: '5px' }}>{activity.meta.level} | {activity.meta.type.toUpperCase()}</div>
                </div>
                <button onClick={downloadPDF} className="download-btn"><Download size={18} /> PDF</button>
              </div>

              <hr style={{ borderColor: '#e5e7eb', margin: '20px 0' }} />

              <div style={{ background: '#f8fafc', padding: '15px', borderRadius: '8px', marginBottom: '25px', borderLeft: '4px solid #4f46e5' }}>
                <h4 style={{ margin: '0 0 5px 0', color: '#4f46e5' }}>Teacher Notes</h4>
                <p style={{ margin: 0, fontSize: '0.9rem', color: '#334155' }}>{activity.teacher_guide.rationale}</p>
              </div>

              <h3 style={{ borderBottom: '2px solid #e2e8f0', paddingBottom: '10px' }}>Student Worksheet</h3>
              <p><em>{activity.student_worksheet.instructions}</em></p>

              {activity.student_worksheet.questions.map((q, i) => (
                <div key={i} style={{ marginBottom: '20px' }}>
                  <div style={{ fontWeight: 600, marginBottom: '5px' }}>{i + 1}. {q.question_text}</div>
                  {q.options && q.options.map(opt => (
                    <div key={opt} style={{ marginLeft: '15px', color: '#475569' }}>☐ {opt}</div>
                  ))}
                  {q.hint && isScaffolded && (
                    <div style={{ fontSize: '0.8rem', color: '#059669', marginTop: '4px' }}>💡 {q.hint}</div>
                  )}
                </div>
              ))}
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', color: '#94a3b8' }}>
              <FileText size={64} style={{ marginBottom: '20px', opacity: 0.2 }} />
              <h3>Ready to build</h3>
              <p>Select your inputs on the left to begin.</p>
            </div>
          )}
        </div>

      </main>
    </div>
  );
}